function [h] = connect_axes( h )
h = linkprop(h,...
{'XDir',...
'YDir',...
'ZDir',...
'XScale',...
'YScale',...
'ZScale',...
'XLim',...
'YLim',...
'ZLim',...
'CameraPosition',...
'CameraPositionMode',...
'CameraTarget',...
'CameraTargetMode',...
'CameraUpVector',...
'CameraUpVectorMode',...
'CameraViewAngle',...
'CameraViewAngleMode',...
'View',...
'Clipping',...
'ClippingStyle'});
end