function [R] = RUt(U,theta)
R = [cos(theta)+U(:,1).^2.*(1-cos(theta)) , U(:,1).*U(:,2).*(1-cos(theta))-U(:,3).*sin(theta) , U(:,1).*U(:,3).*(1-cos(theta))+U(:,2).*sin(theta),...
     U(:,1).*U(:,2).*(1-cos(theta))-U(:,3).*sin(theta) , cos(theta)+U(:,2).^2.*(1-cos(theta)) , U(:,2).*U(:,3).*(1-cos(theta))-U(:,1).*sin(theta),...
     U(:,3).*U(:,1).*(1-cos(theta))-U(:,2).*sin(theta) , U(:,3).*U(:,2).*(1-cos(theta))+U(:,1).*sin(theta) , cos(theta)+U(:,3).^2.*(1-cos(theta))];
end