function [P] = transform_point(T,P,type)
if(strcmpi(type,'mat'))
    P = [bsxfun(@plus,dot(T(:,1: 3),P,2),T(:, 4)) ...
         bsxfun(@plus,dot(T(:,5: 7),P,2),T(:, 8)) ...
         bsxfun(@plus,dot(T(:,9:11),P,2),T(:,12))];
     return;
end
if(strcmpi(type,'dq'))
P = bsxfun(@plus,...
           P,...
           2 * (...
           bsxfun(@minus,...
           bsxfun(@plus,...
                  cross( T(:,2:4), ...
                         bsxfun(@plus,...
                                bsxfun(@plus,cross(T(:,2:4),P,2),P .* T(:,1)),...
                                T(:,6:8)),...
                         2),...
                  T(:,6:8) .* T(:,1)),...
           T(:,2:4) .* T(:,5))...
    ));

% P = P + 2 * (...
%              + cross( T(:,2:4), cross(T(:,2:4),P,2) + P .* T(:,1) + T(:,6:8),2)... 
%              + T(:,6:8) .* T(:,1)...
%              - T(:,2:4) .* T(:,5)...
%             );
    return;
end
end