function [fig] = CreateAnimation3D(Skin,Anim)
clear SkinningStep;

fig = CreateViewer3D('right');
ptc = display_mesh(Skin.M.P,Skin.M.N,Skin.M.S);

frame = uicontrol( fig,...
    'Style', 'slider',...
    'Position', [100, 10, 200, 20],...
    'Min', 1,...
    'Max', 100,...
    'SliderStep', [0.01 0.1],...
    'Value', 1);
addlistener( frame, 'ContinuousValueChange',...
             @(src,event) SkinningStep(ptc,Skin,Anim{floor(src.Value)}) );

end

