function [ax] = CreateForegroundAxes3D(h)
if( nargin == 0 || isempty(h) )
    h = axes;
end
NA = {'Color',...
      'Parent',...
      'HandleVisibility',...
      'PickableParts',...
      'HitTest',...
      'Units', ...
      'Position', ...
      'Visible',...
      'XLimMode',...
      'XLim', ...
      'YLimMode',...
      'YLim', ...
      'XTick','YTick', ...
      'Box',...
      'Clipping',...
      'NextPlot'};
if(isfigure(h))
    fig = h;
end
if(isaxes(h))
    fig = h.Parent;
end
VA = {'none',...
      fig, ...
      'off',...
      'none',...
      'off',...
      'normalized', ...
      [0, 0, 1, 1], ...
      'off', ...
      'manual',...
      [0, 1], ...
      'manual',...
      [0, 1], ...
      [],...
      [], ...
      'off',...
      'off',...
      'add'};
if( isfigure(h) )
    ax = axes(  h, NA, VA );
end
if( isaxes(h) )
    ax = set( h, NA, VA );
end
uistack(ax,'top');
end