function [ID] = color2index(C)
if(isdouble(C))
    C = uint8(C*255);
end
ID = cell2mat(...
              cellfun(@(c) typecast([c(:,1) c(:,2) c(:,3) uint8(0)],'uint32'),...
                      num2cell(C,2),...
                      'UniformOutput',false)...
             );
end